# Generated by Django 4.0.2 on 2022-07-07 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_emailverified_profile_newemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='emailVerified',
            new_name='email_verified',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='newEmail',
            new_name='new_email',
        ),
    ]
