# Generated by Django 4.0.2 on 2022-02-20 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tagify.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField(blank=True, max_length=256)),
                ('html', models.TextField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('tagline', models.TextField(blank=True, max_length=1024)),
                ('description', models.TextField(max_length=8096)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('tags', tagify.models.TagField(null=True, verbose_name='tags')),
                ('repo', models.URLField(blank=True, max_length=256)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='things.category')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('licence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='things.licence')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=256)),
                ('image', models.ImageField(upload_to='images/')),
                ('featured', models.BooleanField(default=False)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='things.thing')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('file', models.FileField(upload_to='files')),
                ('default', models.BooleanField(default=False)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_set', to='things.thing')),
            ],
        ),
    ]
