# Generated by Django 3.2.9 on 2022-02-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0004_remove_image_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='piece',
            new_name='thing',
        ),
    ]
