# Generated by Django 3.2.9 on 2022-02-10 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0005_rename_piece_image_thing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='piece',
            new_name='thing',
        ),
        migrations.AlterField(
            model_name='image',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_set', to='things.thing'),
        ),
    ]
