# Generated by Django 3.2.9 on 2022-02-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0006_auto_20220210_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_set', to='things.thing'),
        ),
    ]
