# Generated by Django 4.0.2 on 2022-02-22 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0006_supercategory_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
