# Generated by Django 3.2.9 on 2022-02-12 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0007_alter_file_thing'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='things.category'),
        ),
    ]
