# Generated by Django 3.2.9 on 2022-02-13 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0008_thing_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('url', models.URLField(blank=True, max_length=256)),
                ('html', models.TextField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='thing',
            name='tagline',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=models.TextField(max_length=8096),
        ),
        migrations.AlterField(
            model_name='thing',
            name='repo',
            field=models.URLField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='thing',
            name='title',
            field=models.CharField(max_length=128),
        ),
        migrations.AddField(
            model_name='thing',
            name='licence',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='things.licence'),
            preserve_default=False,
        ),
    ]
