# Generated by Django 4.0.2 on 2022-02-24 17:42

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0009_file_downloads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='description',
            field=django_bleach.models.BleachField(max_length=8096),
        ),
        migrations.AlterField(
            model_name='thing',
            name='tagline',
            field=django_bleach.models.BleachField(blank=True, max_length=1024),
        ),
    ]
