# Generated by Django 3.2.9 on 2022-02-18 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0009_auto_20220213_1008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
