# Generated by Django 3.2.9 on 2022-02-19 16:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tags', '0002_auto_20220218_2218'),
        ('things', '0010_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thing',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
