# Generated by Django 4.0.2 on 2022-02-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug',
            field=models.CharField(default='non', max_length=127),
            preserve_default=False,
        ),
    ]
