# Generated by Django 4.0.2 on 2022-02-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0008_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
