# Generated by Django 4.0.2 on 2022-02-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0011_thing_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='file',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
