# Generated by Django 4.0.2 on 2022-04-14 20:40

from django.db import migrations, models
import things.validators


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0012_alter_file_options_alter_image_options_file_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='files', validators=[things.validators.validateFileSize]),
        ),
        migrations.AlterField(
            model_name='file',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='order',
            field=models.IntegerField(),
        ),
    ]
