# Generated by Django 4.0.2 on 2022-06-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0013_alter_file_file_alter_file_order_alter_image_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='date_featured',
            field=models.DateTimeField(null=True),
        ),
    ]
