# Generated by Django 4.0.2 on 2022-06-13 19:26

from django.db import migrations, models
import django.db.models.deletion
import things.validators


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0014_thing_date_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_set', to='things.thing', validators=[things.validators.validateNumberOfFiles]),
        ),
    ]
