name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
  
  deploy:
   runs-on: ubuntu-latest
   steps:
   - name: Deploy to Server
     uses: appleboy/ssh-action@master
     with:
        host: ${{secrets.SSH_HOST}}
        key: ${{secrets.SSH_KEY}}
        username: ${{secrets.SSH_USERNAME}}
        
        script: |
          cd /home/adam/osj
          git pull
          source .venv/bin/activate
          python manage.py makemigrations
          python manage.py migrate
          python manage.py collectstatic --noinput
          servie gunicorn restart
          service nginx restart
          deactivate
          echo 'Deployment successful'
